#!/bin/sh
clear

echo "#######################################################################"
echo "# __      __      ___.     _________.__           .__  .__			#"
echo "#/  \    /  \ ____\_ |__  /   _____/|  |__   ____ |  | |  |   ______ 	#"
echo "#\   \/\/   // __ \| __ \ \_____  \ |  |  \_/ __ \|  | |  |  /  ___/	#"
echo "# \        /\  ___/| \_\ \/        \|   Y  \  ___/|  |_|  |__\___ \	#"
echo "#  \__/\  /  \___  >___  /_______  /|___|  /\___  >____/____/____  >	#"
echo "#       \/       \/    \/        \/      \/     \/               \/	#"
echo "#						WS - OS POS Auto Installer						#"
echo "#######################################################################"

  if [ "$1" = "" ]; 
  then echo "OSPOS Retail POS ( OSPOS ) I Is Now Being Copied To $HOME Directory..."
  rm -rf OSPOS
echo "Removing Previous Installations!"
echo ""
echo "Loading =====> 30 % "
echo "Loading ===========> 60 % "
echo "Loading ==================> 90 % "
echo "Loading ======================> 100 % "
echo ""
echo "Welcome To OSPOS, Your Trusted POS Provider!"
 mkdir OSPOS
 cp -R /OSPOS-26719/* ~/OSPOS/
echo ""
echo "Copying files & installing scripts"
echo
echo "OSPOS Retail POS Has Been Successfully Installed In"
echo "Your Home Dir Under $HOME/OSPOS"
echo "If You Like Our Automated System Can Generate The DB Files For You"
echo
echo -n "Shall We Help You Create The DB Files (Y/N)?"
echo
cd
read answer
  if test "$answer" != "Y" -a "$answer" != "y";
  then exit 0;
  else
echo
echo "You Need To Answer Some Questions..."
echo "MySQL DataBase Name?"
  read dbname
echo
echo "MySQL DataBase Username?"
  read usernames
echo
echo "MySQL User Password?"
  read passwd
echo
echo "What's Your Hostname?"
  read hostname
echo
echo "Creating Database Files Now..."
echo ""
mv OSPOS/application/config/database.php OSPOS/application/config/database.php.bk
touch OSPOS/application/config/database.php
echo "<?php" >> $HOME/OSPOS/application/config/database.php
echo "defined('BASEPATH') OR exit('No direct script access allowed');" >> $HOME/OSPOS/application/config/database.php
echo "\$active_group = 'default';" >> $HOME/OSPOS/application/config/database.php
echo "\$query_builder = TRUE;" >> $HOME/OSPOS/application/config/database.php

echo "\$db['default'] = array(" >> $HOME/OSPOS/application/config/database.php
echo "  'dsn'   => ''," >> $HOME/OSPOS/application/config/database.php
echo "  'hostname' => '$hostname'," >> $HOME/OSPOS/application/config/database.php
echo "  'username' => '$(whoami)_$usernames'," >> $HOME/OSPOS/application/config/database.php
echo "  'password' => '$passwd'," >> $HOME/OSPOS/application/config/database.php
echo "  'database' => '$(whoami)_$dbname'," >> $HOME/OSPOS/application/config/database.php
echo "  'dbdriver' => 'mysqli'," >> $HOME/OSPOS/application/config/database.php
echo "  'dbprefix' => 'ospos_'," >> $HOME/OSPOS/application/config/database.php
echo "  'pconnect' => FALSE," >> $HOME/OSPOS/application/config/database.php
echo "  'db_debug' => (ENVIRONMENT !== 'production')," >> $HOME/OSPOS/application/config/database.php
echo "  'cache_on' => FALSE," >> $HOME/OSPOS/application/config/database.php
echo "  'cachedir' => ''," >> $HOME/OSPOS/application/config/database.php
echo "  'char_set' => 'utf8'," >> $HOME/OSPOS/application/config/database.php
echo "  'dbcollat' => 'utf8_general_ci'," >> $HOME/OSPOS/application/config/database.php
echo "  'swap_pre' => ''," >> $HOME/OSPOS/application/config/database.php
echo "  'encrypt' => FALSE," >> $HOME/OSPOS/application/config/database.php
echo "  'compress' => FALSE," >> $HOME/OSPOS/application/config/database.php
echo "  'stricton' => FALSE," >> $HOME/OSPOS/application/config/database.php
echo "  'failover' => array()," >> $HOME/OSPOS/application/config/database.php
echo "  'save_queries' => TRUE" >> $HOME/OSPOS/application/config/database.php
echo ");" >> $HOME/OSPOS/application/config/database.php
echo ""
echo "Loading ===> 20 % "
echo "Loading =======> 44 % "
echo "Loading ==============> 60 % "
echo "Loading =================> 72 % "
echo "Loading ======================> 100 % "
fi
echo "**********************************************"
echo ""
echo "Database Config Files Created Successfully!"
echo "Available under $HOME/OSPOS/application/config/ as database.php"
echo
echo -n "Do You Want To Import OSPOS Retail POS Default DB (Y/N)?"
echo
read answer
  if test "$answer" != "Y" -a "$answer" != "y";
  then exit 0;
  else
echo "MySQL Database & User Created Successfully!"
echo "Importing Default DB Values"
echo ""
#sql="CREATE DATABASE IF NOT EXISTS $dbname CHARACTER SET utf8;CREATE USER '$usernames'@'localhost' IDENTIFIED BY '$passwd';GRANT ALL PRIVILEGES ON $dbname.* TO '$usernames'@'localhost' IDENTIFIED BY '$pass$
#mysql -hlocalhost -u $(whoami) -p -e "$sql"
/usr/bin/uapi  Mysql create_database name=$(whoami)_$dbname > /dev/null 2>&1
/usr/bin/uapi  Mysql create_user name=$(whoami)_$usernames password=$passwd > /dev/null 2>&1
/usr/bin/uapi  Mysql set_privileges_on_database user=$(whoami)_$usernames database=$(whoami)_$dbname privileges=ALL%20PRIVILEGES > /dev/null 2>&1
mysql -hlocalhost -u $(whoami)_$usernames -p$passwd $(whoami)_$dbname < $HOME/OSPOS/OSPOSSQL.sql 

echo "27 SQL Tables Created"
echo ""
echo "Loading =======> 47 % "
echo "Loading =================> 71 % "
echo "Loading ======================> 100 % "
fi
echo
mv $HOME/OSPOS $HOME/public_html/OSPOS/
echo "**************************************************"
echo ""
echo "If You filled in the needed, The Installation Of"
echo "OSPOS Should Be Running Now On Link:"
echo ""
echo "https://$hostname/OSPOS/public"
echo ""
echo "Use below credentials in order to login to our POS"
echo ""
echo "Username: admin"
echo "Password: pointofsale"
echo ""
echo "Please keep the DB credentials safe!"
echo ""
echo "Database: $dbname"
echo "Username: $usernames"
echo "Password: $passwd"
echo
echo "**************************************************"
echo
echo "Enjoy Our Retail Solution OSPOS"
echo "   http://ospos.wshells.org"
echo
exit 0
fi
-
